# Este é um fluxo de trabalho básico para ajudar você a começar com ações

name: CI

# Controla quando o fluxo de trabalho será executado
on:
  # Aciona o fluxo de trabalho em push ou pull request
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Permite executar manualmente
  workflow_dispatch:

# Trabalhos do fluxo
jobs:
  build:

    # Sistema operacional usado
    runs-on: ubuntu-latest

    # Etapas do trabalho
    steps:

      # Faz checkout do repositório
      - uses: actions/checkout@v3

      # Executa um comando simples
      - name: Executa um script de uma linha
        run: echo "Olá, mundo!"

      # Executa vários comandos
      - name: Executa um script multi-linha
        run: |
          echo "Adicionar outras ações para construir"
          echo "testar e implantar seu projeto"
